name: Existing Env from Github Artifact

on:
  workflow_call:
    inputs:
      version: # the variable you can use in place of a matrix
        required: true
        type: string

jobs:
  download_conda_packd_envs:
    #inputs.version is from the workflow call from the main yml file
    name: ${{ inputs.version }} Python for Conda packed env
    runs-on: ubuntu-latest
    outputs:
      test_conda_packed_name: ${{ env.TEST_ENV_NAME }}
    env:
      TZ: America/New_York

#    defaults:
#      run:
#        shell: bash -lvxeo pipefail {0}

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Install Python for YAML CLI tools
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install YAML CLI tools
        run: |
          python3 -m pip install shyaml

      - name: Set env vars
        # Most importantly creates the Conda Environment name whose format is year-version-pythonversion-tiled
        run: |
          set -vxeuo pipefail

          export REPOSITORY_NAME=${GITHUB_REPOSITORY#*/}  # just the repo, as opposed to org/repo
          echo "REPOSITORY_NAME=${REPOSITORY_NAME}" >> $GITHUB_ENV

          export DATETIME_STRING=$(date +%Y%m%d%H%M%S)
          echo "DATETIME_STRING=${DATETIME_STRING}" >> $GITHUB_ENV

          export PYTHONVER=$(echo ${{ inputs.version }} | sed 's/\.//g')
          echo "PYTHONVER=${PYTHONVER}" >> $GITHUB_ENV

          export CONDA_PACK_TEMPLATE_DIR=${HOME}/conda-pack-template
          echo "CONDA_PACK_TEMPLATE_DIR=${CONDA_PACK_TEMPLATE_DIR}" >> $GITHUB_ENV

          env_name=$(cat configs/config-py${PYTHONVER}.yml | shyaml get-value env_name)
          export CONDA_PACK_ENV_NAME=${env_name}
          echo "CONDA_PACK_ENV_NAME=${CONDA_PACK_ENV_NAME}" >> $GITHUB_ENV
  
          env | sort -u
          echo "$GITHUB_ENV"
      - name: Download Artifacts from Github Repo
        env:
          GH_TOKEN: ${{ github.token }}
          GHA_TOKEN: ${{ github.token }}
        run: |
          export ARTIFACTS_DIR="$HOME/artifacts"
          echo "ARTIFACTS_DIR=${ARTIFACTS_DIR}" >> $GITHUB_ENV
          if [ ! -d "${ARTIFACTS_DIR}" ]; then
              mkdir -v -p "${ARTIFACTS_DIR}"
          fi
          python3 download_from_github.py -o "nsls2-conda-envs" -a "10189092932" -r "nsls2-collection-tiled" -p ${{ env.PYTHONVER }}
          mv *${{ env.CONDA_PACK_ENV_NAME }}* "${ARTIFACTS_DIR}"
          echo "moving results"
          ls "${ARTIFACTS_DIR}"
          

      - name: Contents of the env .yml file
        run: |
          cat ${ARTIFACTS_DIR}/${CONDA_PACK_ENV_NAME}.yml.txt

      - name: Checksum files
        run: |
          cat ${ARTIFACTS_DIR}/*sum.txt

      # https://github.com/actions/upload-artifact
      - name: Upload artifacts for the env .yml file
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.CONDA_PACK_ENV_NAME }}.yml
          path: ${{ env.ARTIFACTS_DIR }}/${{ env.CONDA_PACK_ENV_NAME }}.yml.txt
          retention-days: 60

      - name: Upload artifacts for branch
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.CONDA_PACK_ENV_NAME }}
          path: ${{ env.ARTIFACTS_DIR }}
          retention-days: 14

      - name: passing output
        run: echo "TEST_ENV_NAME=${{ env.CONDA_PACK_ENV_NAME }}" >> $GITHUB_ENV

  testing_conda_artifact:
    name: ${{ matrix.repos.beamline_acronym }}-${{ inputs.version }}
    needs: download_conda_packd_envs
    env:
      REPO_URL: "https://github.com/${{matrix.repos.org}}/${{matrix.repos.repo}}"
    strategy:
      fail-fast: false
      matrix:
        repos:
          - org: "NSLS-II-CSX"
            repo: "profile_collection"
            branch: "master"
            beamline_acronym: "csx"
          - org: "NSLS-II-SRX"
            repo: "profile_collection"
            branch: "master"
            beamline_acronym: "srx"
          - org: "NSLS-II-SIX"
            repo: "profile_collection"
            branch: "master"
            beamline_acronym: "six"
          - org: "NSLS-II-HXN"
            repo: "profile_collection"
            branch: "master"
            beamline_acronym: "hxn"
          - org: "NSLS-II-ISR"
            repo: "profile_analysis"
            branch: "master"
            beamline_acronym: "isr"
          - org: "NSLS-II-BMD"
            repo: "profile_collection"
            branch: "master"
            beamline_acronym: "bmm"
          - org: "NSLS-II-QAS"
            repo: "profile_collection"
            branch: "master"
            beamline_acronym: "qas"
    runs-on: ubuntu-latest
    steps:
      - run: echo "TEST_CONDA_PACKED_NAME=${{ needs.download_conda_packd_envs.outputs.test_conda_packed_name }}" >> $GITHUB_ENV
      - name: using test-action
        uses: nsls2-conda-envs/beamline-integration-test@v0.1
        with:
          run-id: "${{ github.run_id }}"
          test-conda-packed-name: "${{ env.TEST_CONDA_PACKED_NAME }}"
          org: "${{ matrix.repos.org }}"
          repo: "${{ matrix.repos.repo }}"
          branch: "${{ matrix.repos.branch }}"
          beamline-acronym: "${{ matrix.repos.beamline_acronym }}"
  report_generation:
    needs: testing_conda_artifact
    if: |
      always() &&
      (needs.testing_conda_artifact.result == 'success' || needs.testing_conda_artifact.result == 'failure')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Set Up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - name: Running Script To Get Job Info To md File
        env:
          MD_FILE_NAME: markdown_file
          GH_TOKEN: ${{ github.token }}
        run: |
          python3 beamline_status_to_md.py -p "${{ inputs.version }}" -a "${{ github.run_id }}" -m "$MD_FILE_NAME"
          cat "$MD_FILE_NAME.md"
          cp "$MD_FILE_NAME.md" $GITHUB_STEP_SUMMARY
